services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: streem_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    restart: unless-stopped
    
  db:
    image: postgres:16-alpine
    container_name: streem_db
    environment:
      POSTGRES_USER: streem
      POSTGRES_PASSWORD: streem
      POSTGRES_DB: streem_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streem -d streem_dev"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: streem_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
  
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: streem_opensearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_PASSWORD:-Vinay@Open5e@rch}
      logger.level: WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9600:9600"
      - "9201:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status'"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.20.4
    container_name: streem_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  neo4j:
    image: neo4j:5.24
    container_name: streem_neo4j
    ports:
      - "7474:7474"   # HTTP UI
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-Vinay@neo4j}
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 512m
      NEO4J_server_memory_pagecache_size: 512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME:-neo4j} -p ${NEO4J_PASSWORD:-Vinay@neo4j} 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    environment:
      DATABASE_URL: postgresql+psycopg://streem:streem@db:5432/streem_dev
      REDIS_URL: redis://redis:6379/0
      ENV: development
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      SESSION_COOKIE_NAME: sid
      SESSION_TTL_SECONDS: 604800
      SESSION_SECRET: ${SESSION_SECRET:-changeme}
      PYTHONUNBUFFERED: "1"
      S3_ENDPOINT: http://minio:9000
      S3_PUBLIC_ENDPOINT: http://localhost:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_REGION: us-east-1
      S3_BUCKET: media
      S3_USE_SSL: "false"
      OPENSEARCH_URL: http://opensearch:9200
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-opensearchadmin}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-Vinay@Open5e@rch}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_CHAT_MODEL: gpt-5-mini
      OPENAI_EMBEDDING_MODEL: text-embedding-3-small
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: ${NEO4J_USERNAME:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-Vinay@neo4j}
      NEO4J_DATABASE: neo4j
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
      opensearch:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: sh -c "uvicorn worker:app --host 0.0.0.0 --port 9100 --reload"
    ports:
      - "9100:9100"
    volumes:
      - ./apps/api:/app
    environment:
      DATABASE_URL: postgresql+psycopg://streem:streem@db:5432/streem_dev
      REDIS_URL: redis://redis:6379/0
      ENV: development
      SESSION_COOKIE_NAME: sid
      SESSION_TTL_SECONDS: 604800
      SESSION_SECRET: ${SESSION_SECRET:-changeme}
      PYTHONUNBUFFERED: "1"
      S3_ENDPOINT: http://minio:9000
      S3_PUBLIC_ENDPOINT: http://localhost:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_REGION: us-east-1
      S3_BUCKET: media
      S3_USE_SSL: "false"
      FFMPEG_BIN: ffmpeg
      FFPROBE_BIN: ffprobe
      FFMPEG_TIMEOUT_720P_SECONDS: 1200
      FFMPEG_TIMEOUT_480P_SECONDS: 900
      THUMBNAIL_TIMEOUT_SECONDS: 30
      FFPROBE_TIMEOUT_SECONDS: 30
      WORKER_LOCK_TTL_MS: 900000
      WORKER_BACKOFF_SECONDS: 30,120,300
      OPENSEARCH_URL: http://opensearch:9200
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-opensearchadmin}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-Vinay@Open5e@rch}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_CHAT_MODEL: gpt-5-mini
      OPENAI_EMBEDDING_MODEL: text-embedding-3-small
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: ${NEO4J_USERNAME:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-Vinay@neo4j}
      NEO4J_DATABASE: neo4j
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
      opensearch:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    restart: unless-stopped

  notifier:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: sh -c "uvicorn notifier:app --host 0.0.0.0 --port 9200 --reload"
    ports:
      - "9200:9200"
    volumes:
      - ./apps/api:/app
    environment:
      DATABASE_URL: postgresql+psycopg://streem:streem@db:5432/streem_dev
      REDIS_URL: redis://redis:6379/0
      ENV: development
      SESSION_COOKIE_NAME: sid
      SESSION_TTL_SECONDS: 604800
      SESSION_SECRET: ${SESSION_SECRET:-changeme}
      PYTHONUNBUFFERED: "1"
      EMAIL_ENABLED: "true"
      EMAIL_FROM: dev@streem.local
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_STARTTLS: "false"
      SMTP_SSL: "false"
      PUBLIC_WEB_BASE_URL: http://localhost:3000
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    command: sh -c "npm ci && npm run dev -- -p 3000 -H 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  web_node_modules:
  web_next:
  minio_data:
  minio_config:
  opensearch_data:
  neo4j_data:
  neo4j_logs: