# k8s/app/notifier.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: streem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: python:3.11-slim
        command:
        - sh
        - -c
        - |
          pip install --no-cache-dir -r /app/requirements.txt
          cd /app && uvicorn notifier:app --host 0.0.0.0 --port 9200 --reload
        ports:
        - containerPort: 9200
          name: http
        envFrom:
        - secretRef:
            name: streem-secrets
        - configMapRef:
            name: streem-config
        volumeMounts:
        - name: notifier-code
          mountPath: /app
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /ready
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 30 # 5 minute window
        livenessProbe:
          httpGet:
            path: /ready
            port: 9200
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 9200
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: notifier-code
        hostPath:
          path: /streem/apps/api
          type: Directory

---
# ClusterIP service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: streem
spec:
  selector:
    app: notifier
  ports:
  - port: 9200
    targetPort: 9200
    name: http

---
# NodePort service for debugging access (localhost:9200)
apiVersion: v1
kind: Service
metadata:
  name: notifier-external
  namespace: streem
spec:
  type: NodePort
  selector:
    app: notifier
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30006
    name: http
