# k8s/app/worker.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: streem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: python:3.11-slim
        command:
        - sh
        - -c
        - |
          apt-get update && apt-get install -y ffmpeg
          pip install --no-cache-dir -r /app/requirements.txt
          cd /app && uvicorn worker:app --host 0.0.0.0 --port 9100 --reload
        ports:
        - containerPort: 9100
          name: http
        envFrom:
        - secretRef:
            name: streem-secrets
        - configMapRef:
            name: streem-config
        volumeMounts:
        - name: worker-code
          mountPath: /app
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        startupProbe:
          httpGet:
            path: /ready
            port: 9100
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 30 # 5 minute window
        livenessProbe:
          httpGet:
            path: /ready
            port: 9100
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 9100
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: worker-code
        hostPath:
          path: /streem/apps/api
          type: Directory

---
# ClusterIP service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: streem
spec:
  selector:
    app: worker
  ports:
  - port: 9100
    targetPort: 9100
    name: http

---
# NodePort service for debugging access (localhost:9100)
apiVersion: v1
kind: Service
metadata:
  name: worker-external
  namespace: streem
spec:
  type: NodePort
  selector:
    app: worker
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 30005
    name: http
