"""video intelligence tables

Revision ID: 14366d6acf59
Revises: 6b5b3b8e03a4
Create Date: 2025-10-11 01:49:03.883897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14366d6acf59'
down_revision: Union[str, Sequence[str], None] = '6b5b3b8e03a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_entities_canonical_name'))
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_topics_canonical_name'))
    )
    op.create_table('video_chapters',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('chapters', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_chapters_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_video_chapters'))
    )
    op.create_table('video_entities',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_video_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_entities_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'entity_id', name=op.f('pk_video_entities'))
    )
    op.create_index('ix_video_entities_entity_video', 'video_entities', ['entity_id', 'video_id'], unique=False)
    op.create_table('video_summary',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_summary_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_video_summary'))
    )
    op.create_table('video_tags',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_tags_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'tag', name=op.f('pk_video_tags'))
    )
    op.create_index('ix_video_tags_tag', 'video_tags', ['tag'], unique=False)
    op.create_table('video_topics',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('prominence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_video_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_topics_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'topic_id', name=op.f('pk_video_topics'))
    )
    op.create_index('ix_video_topics_topic_video', 'video_topics', ['topic_id', 'video_id'], unique=False)
    op.add_column('videos', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('language', sa.String(), server_default='en', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'language')
    op.drop_column('videos', 'content_type')
    op.drop_index('ix_video_topics_topic_video', table_name='video_topics')
    op.drop_table('video_topics')
    op.drop_index('ix_video_tags_tag', table_name='video_tags')
    op.drop_table('video_tags')
    op.drop_table('video_summary')
    op.drop_index('ix_video_entities_entity_video', table_name='video_entities')
    op.drop_table('video_entities')
    op.drop_table('video_chapters')
    op.drop_table('topics')
    op.drop_table('entities')
    # ### end Alembic commands ###
