"""add tags + video_tags

Revision ID: c75e70968f17
Revises: 8e6acaadf5e4
Create Date: 2025-10-15 02:22:43.165604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75e70968f17'
down_revision: Union[str, Sequence[str], None] = '8e6acaadf5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_tags_canonical_name'))
    )
    op.create_table('video_tags',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_video_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_tags_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'tag_id', name=op.f('pk_video_tags'))
    )
    op.create_index('ix_video_tags_tag_video', 'video_tags', ['tag_id', 'video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_tags_tag_video', table_name='video_tags')
    op.drop_table('video_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
