"""create_watch_history

Revision ID: cfbea6482b65
Revises: b1a2c3d4e5f6
Create Date: 2025-09-19 18:26:13.928021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbea6482b65'
down_revision: Union[str, Sequence[str], None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('last_position_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watch_history_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_watch_history_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'video_id', name=op.f('pk_watch_history'))
    )
    op.create_index('ix_watch_history_user_lastwatched', 'watch_history', ['user_id', 'last_watched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_history_user_lastwatched', table_name='watch_history')
    op.drop_table('watch_history')
    # ### end Alembic commands ###
