# k8s/stateful/neo4j.yaml

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: streem
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.24
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: streem-secrets
              key: NEO4J_AUTH
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: streem-secrets
              key: NEO4J_PASSWORD
        - name: NEO4J_PLUGINS
          value: '["graph-data-science"]'
        - name: NEO4J_server_memory_heap_initial__size
          value: "1g"
        - name: NEO4J_server_memory_heap_max__size
          value: "2g"
        - name: NEO4J_server_memory_pagecache_size
          value: "1g"
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: logs
          mountPath: /logs
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - cypher-shell -u neo4j -p "${NEO4J_PASSWORD}" "RETURN 1"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - cypher-shell -u neo4j -p "${NEO4J_PASSWORD}" "RETURN 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - cypher-shell -u neo4j -p "${NEO4J_PASSWORD}" "RETURN 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi

---
# Headless service for direct pod access
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: streem
spec:
  clusterIP: None
  selector:
    app: neo4j
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: bolt

---
# NodePort service for external access (localhost:7474 and localhost:7687)
apiVersion: v1
kind: Service
metadata:
  name: neo4j-external
  namespace: streem
spec:
  type: NodePort
  selector:
    app: neo4j
  ports:
  - port: 7474
    targetPort: 7474
    nodePort: 30474
    name: http
  - port: 7687
    targetPort: 7687
    nodePort: 30687
    name: bolt

